In [12]:
import cv2 as cv

In [13]:
#read image
image = cv.imread("../DATA/image1.png")

In [14]:
# show 
def show(img):
    # using cv
    cv.imshow("image", img)
    cv.waitKey(0)
    cv.destroyAllWindows()
# show(image)

In [15]:
gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
show(gray)

In [16]:
print(image.shape)

(512, 512, 3)


In [17]:
print(gray.shape)

(512, 512)


In [18]:
rgb_image = cv.imread("../DATA/rgb_image.jpg")
show(rgb_image)

In [19]:
rgb_image = cv.cvtColor(rgb_image, cv.COLOR_BGR2RGB)
show(rgb_image)

In [20]:
print(rgb_image.shape)

(360, 639, 3)


In [21]:
print(rgb_image)

[[[48 23 19]
  [47 22 18]
  [49 21 18]
  ...
  [ 2  3 23]
  [ 2  3 23]
  [ 2  3 23]]

 [[47 22 18]
  [47 22 18]
  [49 21 18]
  ...
  [ 3  4 24]
  [ 3  4 24]
  [ 3  4 24]]

 [[49 21 20]
  [48 20 19]
  [49 19 17]
  ...
  [ 3  4 24]
  [ 3  4 24]
  [ 3  4 24]]

 ...

 [[ 9  5 28]
  [ 9  5 28]
  [ 9  5 28]
  ...
  [13 10 27]
  [12  9 26]
  [12  9 26]]

 [[ 9  5 28]
  [ 9  5 28]
  [ 9  5 28]
  ...
  [11  9 23]
  [12 10 24]
  [13 11 25]]

 [[ 9  5 28]
  [ 9  5 28]
  [ 9  5 28]
  ...
  [14 12 26]
  [16 14 28]
  [19 17 31]]]


In [22]:
rgb_image_1 = cv.imread("../DATA/colors.jpg")
rgb_image_1 = cv.cvtColor(rgb_image_1, cv.COLOR_BGR2RGB)


In [23]:
(R,G,B) = cv.split(image)

In [24]:
cv.namedWindow("Blue", cv.WINDOW_NORMAL)
cv.namedWindow("Green", cv.WINDOW_NORMAL)
cv.namedWindow("Red", cv.WINDOW_NORMAL)

In [25]:
cv.imshow("Blue" , B)
cv.imshow("Green", G)
cv.imshow("Red", R)

In [26]:
cv.imwrite("channel_red.jpg", R)
cv.imwrite("channel_green.jpg", G)
cv.imwrite("channel_blue.jpg", B)
if cv.waitKey(0):
    cv.destroyAllWindows()

In [27]:
rgb_image_1 = cv.imread("../DATA/colors.jpg")
(b,g,r) = rgb_image_1[0,0]
print(f"At pixel (0,0), - Red: {r} , Green: {g}, Blue {b}")

At pixel (0,0), - Red: 42 , Green: 141, Blue 12


### Drawing

In [28]:
import numpy as np
import cv2 as cv

In [29]:
canvas = np.zeros((300, 300, 3), dtype="uint8")

In [30]:
green = (0,255,0)
cv.line(canvas, (0,0), (300,300), green)
show(canvas)

In [31]:
red = (0,0,255)
cv.line(canvas, (300,0), (0,300), red)
show(canvas)

In [32]:
cv.rectangle(canvas, (50,200),(200,225),red, 5)
show(canvas)

In [33]:
blue = (255, 0 ,0)
cv.rectangle(canvas, (50,200),(200,225),blue, -1)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

13

In [34]:
canvas = np.zeros((300,300,3), dtype="uint8")
canvas.shape

(300, 300, 3)

In [35]:
(centerX, centerY) = (canvas.shape[1] // 2 , canvas.shape[0] // 2 )
white = (255,255,255)


In [36]:
print(centerX, centerY)

150 150


In [37]:
for r in range(0,175,25):
    cv.circle(canvas, (centerX, centerY), r, white )
cv.imshow("Canvas" , canvas)
cv.waitKey(0)

13

In [38]:
for i in range(0,25):
    radius = np.random.randint(5, high=200)
    color = np.random.randint(0, high=200, size = (3,)).tolist()
    pt = np.random.randint(0, high=300,size=(2,)) 
    cv.circle(canvas, pt, radius, color, -1)
    
show(canvas)