In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

### Tensorflow Tensor

In [8]:

# TensorFlow Constant
a = tf.constant(5.0)
b = tf.constant(10.0)

# TensorFlow Variable
x = tf.Variable(3.0)

# Perform operations using constants and variables
result = a * x + b

# Print the result
print("Result of a * x + b:", result.numpy())
print(type(result))
print(result.device)

Result of a * x + b: 25.0
<class 'tensorflow.python.framework.ops.EagerTensor'>
/job:localhost/replica:0/task:0/device:CPU:0


In [10]:
# Update the variable
x.assign(4)

# Perform the operation again with updated variable
new_result = a * x + b
print("New result after updating x:", new_result.numpy())

New result after updating x: 30.0


In [15]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
c = tf.add(a, b)
print(c)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


### Tensorflow Placeholders

**Placeholders (tf.placeholder):**
These were used as inputs to the graph where the values would be provided at runtime via feed_dict. 

They allowed dynamic input feeding during the execution of the graph.

**Session:** In TensorFlow 1.x, you needed to create a tf.Session() to run operations, and placeholders required you to feed values into them during session execution.

In [17]:
# TensorFlow 1.x (use in legacy code or TensorFlow 1.x environments)
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


# Placeholder for input values
x = tf.placeholder(dtype=tf.float32, shape=None)

# Constant
a = tf.constant(4.0) #todo: create a constant
b =  tf.constant(5.0) #todo: create a constant

# Define an operation
result = a * x + b

# Create a session to run the computation graph
with tf.Session() as sess:
    # Feed a value into the placeholder and execute the graph
    result_value = sess.run(result, feed_dict={x: 3.0})  # Example: x=3.0
    print("Result with placeholder:", result_value)


Result with placeholder: 17.0


**TensorFlow 2.x:** Focuses on constants (tf.constant) and variables (tf.Variable). 

Eager execution removes the need for placeholders or sessions.

**TensorFlow 1.x:** Used placeholders (tf.placeholder) for feeding data into graphs at runtime and required sessions to execute the graph.

In [1]:
# TensorFlow v2
import tensorflow as tf

### Tensorflow: Tensor Operations

In [2]:

sum_result = tf.add([1,2,3], [1,2,3]) # Addition
diff_result = tf.subtract([1,2,3], [1,2,3]) # Subtraction
quot_result = tf.divide([1,2,3], [1,2,3]) # Division
prod_result = tf.multiply([1,2,3], [1,2,3]) # Multiplication

print("Sum of Tensors", sum_result.numpy())
print("Difference of tensors", diff_result.numpy())
print("Quotient of Tensor", quot_result.numpy())
print("Product of tensors ", prod_result.numpy())



Sum of Tensors [2 4 6]
Difference of tensors [0 0 0]
Quotient of Tensor [1. 1. 1.]
Product of tensors  [1 4 9]


In [ ]:
# Element-wise operations
a = tf.constant([1, 2, 3]) # 6
b = tf.constant([2, 1, 3]) # 6
min_result = tf.minimum(a, b)
max_result = tf.maximum(a, b)
abs_result = tf.abs(a)

print("Minimum:", min_result)
print("Maximum:", max_result)
print("Absolute value:", abs_result)


Minimum: tf.Tensor([-1  1  3], shape=(3,), dtype=int32)
Maximum: tf.Tensor([2 2 3], shape=(3,), dtype=int32)
Absolute value: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [10]:
a.dtype

tf.int32

In [11]:
# Cast the tensor `a` to float32 to match the type of 1e-8
a = tf.cast(a, dtype=tf.float32)

In [12]:
a.dtype

tf.float32

In [13]:
# Now you can safely compute the logarithm
log_result = tf.math.log(tf.maximum(a, 1e-8))  # Ensure positive values for logarithm
exp_result = tf.math.exp(a)


print("Logarithm:", log_result)
print("Exponential:", exp_result)


Logarithm: tf.Tensor([-18.420681    0.6931472   1.0986123], shape=(3,), dtype=float32)
Exponential: tf.Tensor([ 0.36787945  7.389056   20.085537  ], shape=(3,), dtype=float32)


In [14]:
a = tf.constant([3, 3, 3]) #todo: create a tensor

scalar = tf.constant(2) #todo: create a constant
broadcast_result = tf.add(a, scalar)
print("Broadcasted Addition:", broadcast_result)


Broadcasted Addition: tf.Tensor([5 5 5], shape=(3,), dtype=int32)


In [15]:
sum_axis = tf.reduce_sum(a, axis=0)  # Sum across the first axis
mean_axis = tf.reduce_mean(a, axis=0)  # Mean across the second axis
print("Sum across axis 0:", sum_axis)
print("Mean across axis 0:", mean_axis)


Sum across axis 0: tf.Tensor(9, shape=(), dtype=int32)
Mean across axis 0: tf.Tensor(3, shape=(), dtype=int32)


#### Matmul example

In [ ]:
import tensorflow as tf

# Example: Input data for a neural network layer
#todo: create input data tensor of shape (2,2), same for weights
# input_data = tf.constant([
#     [1.0 , 2.0],
#     [3.0, 4.0]
# ])   # Shape: (2, 2)
# weights = tf.constant([
#     [0.3, 0.4],
#     [0.2, 0.1]
# ])       # Shape: (2, 2)

input_data = tf.constant([
    [1.0],
    [3.0],
    [1.0]
])   # Shape: (3, 1)
weights = tf.constant([
    [0.3, 0.4, 0.2],
])       # Shape: (1, 3)

# Matrix multiplication between input and weights
output = tf.matmul(input_data, weights)
print("Neural Network Layer Output:\n", output)


Neural Network Layer Output:
 tf.Tensor(
[[0.3        0.4        0.2       ]
 [0.90000004 1.2        0.6       ]
 [0.3        0.4        0.2       ]], shape=(3, 3), dtype=float32)


#### Multiply Example (Element Wise)

In [22]:
import tensorflow as tf

# Example: Simulating image pixel values
image = tf.constant([[255, 128], [64, 32]], dtype=tf.float32)  # Shape: (2, 2)

# Scaling factor for each pixel (element-wise multiplication)
#for example, you want to minimize the size of the image by halfw
scaling_factor = 0.5
scaled_image = tf.multiply(image, scaling_factor)
print("Scaled Image:\n", scaled_image)


Scaled Image:
 tf.Tensor(
[[127.5  64. ]
 [ 32.   16. ]], shape=(2, 2), dtype=float32)


#### Multiply Example

In [ ]:
import tensorflow as tf

# Example: Simulating a sequence of words (embeddings)
sequence = tf.constant([
    [1.0, 5.0, 2.0],
    [3.0, 2.0, 1.0],
    [4.0, 6.0, 3.0]
])  # Shape: (3, 3)

# Attention scores (one for each word in the sequence)
attention_scores = tf.constant([
    [0.2, 0.3, 0.5],
    [0.4, 0.1, 0.5],
    [0.3, 0.2, 0.5]
])  #Shape: (3, 3)

# Apply attention weights using element-wise multiplication
weighted_sequence = tf.multiply(sequence, attention_scores)
print("Weighted Sequence:\n", weighted_sequence)


Weighted Sequence:
 tf.Tensor(
[[0.2 1.5 1. ]
 [1.2 0.2 0.5]
 [1.2 1.2 1.5]], shape=(3, 3), dtype=float32)


#### Gradient Derivates

In [ ]:
x = tf.Variable(1.0)

def f(x):
  y = x**2 + 2*x - 5
  return y

In [ ]:
with tf......() as tape: #use GradientTape to calculate gradients
  y = f(x)

g_x = tape.gradient(y, x)  # g(x) = dy/dx

g_x

### Tensorflow: Tensor vs Numpy Ndarray
Let's do some benchmarking

In [ ]:
import time
import numpy as np
import tensorflow as tf

# Create large random matrices
size = 10000
np_matrix_a = np.random.randn(size, size)
np_matrix_b = np.random.randn(size, size)
tf_matrix_a = tf.random.normal((size, size))
tf_matrix_b = tf.random.normal((size, size))

# Benchmark NumPy
start_time = time.time()
np_result = np.dot(np_matrix_a, np_matrix_b)
np_duration = time.time() - start_time

# Benchmark TensorFlow on CPU
start_time = time.time()
tf_result = tf.matmul(tf_matrix_a, tf_matrix_b)
tf_duration = time.time() - start_time

print("NumPy Duration: {:.6f} seconds".format(np_duration))
print("TensorFlow (CPU) Duration: {:.6f} seconds".format(tf_duration))


In [ ]:

# Example forward propagation in Python
def forward_propagation(X, W, b):
    Z = np.dot(W, X) + b  # Weighted sum
    A = 1 / (1 + np.exp(-Z))  # Sigmoid activation function
    return A

# Dummy data
X = np.array([[1.0], [2.0], [3.0]])  # Input
W = np.array([[0.2, 0.4, 0.6]])  # Weights
b = np.array([[0.5]])  # Bias

# Forward propagation
output = forward_propagation(X, W, b)
print("Output of forward propagation:", output)


In [ ]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return .....

# ReLU activation function
def relu(x):
    return np....(0, x) 

# Tanh activation function
def tanh(x):
    return np.....(x)

# Example of activation functions
x = np.array([-1.0, 0.0, 1.0, 2.0])
print("Sigmoid:", sigmoid(x))
print("ReLU:", relu(x))
print("Tanh:", tanh(x))


In [ ]:
def forward_with_activation(X, W, b, activation_function):
    Z = np.dot(W, X) + b  # Weighted sum
    match activation_function:
        case 'sigmoid': 
            A = sigmoid(Z)
        case 'relu' : 
            A = relu(Z)
        case 'tanh' :
            A = tanh(Z)
    return A

# Testing the function
W = np.array([[0.2, 0.4, 0.6]])
b = np.array([[0.5]])
X = np.array([[1.0], [2.0], [3.0]])

output = forward_with_activation(X, W, b, activation_function='relu')
print("Output with ReLU activation:", output)
